import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Layout from "./components/layout";
import colors from "colors"
colors.enable()

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // console.log("Enter me")
  return (
    <html lang="en">
      {/* <body className={inter.className}> */}
      <body >
        <main>
          <Layout>
            {children}
          </Layout>
        </main>
      </body>
    </html>
  );
}
