import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TodoFormProvider } from "./contexts/todo.context";
import { TodoDialogProvider } from "./contexts/dialog.context";
// import { CustomDialogProvider } from "./components/CreateTodoDialog";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <TodoDialogProvider>
            <TodoFormProvider>
              {children}
            </TodoFormProvider>
          </TodoDialogProvider>
      </body>
    </html>
  );
}
